"""POST /print: Chromium prints the web app's HTML, the drawn template is the
never-blank fallback. Chromium tests skip only where Chromium cannot launch."""
import base64
import re
from pathlib import Path

import pymupdf
import pytest
from fastapi.testclient import TestClient

from app import main, printer


@pytest.fixture(scope="session")
def chromium():
    try:
        from playwright.sync_api import sync_playwright

        with sync_playwright() as p:
            p.chromium.launch().close()
    except Exception as exc:  # missing package, missing browser, no sandbox
        pytest.skip(f"chromium unavailable: {exc}")


@pytest.fixture
def client(chromium):
    with TestClient(main.app) as c:
        yield c


def _page(blocks: str) -> str:
    return (
        "<!doctype html><html><head><meta charset='utf-8'><style>"
        "@page{size:A4;margin:40pt} body{font:12pt sans-serif;margin:0}"
        ".rz-block{break-inside:avoid;margin:0 0 10pt}"
        f"</style></head><body>{blocks}</body></html>"
    )


HTML = _page(
    "<p class='rz-block'>Priya Sharma</p>"
    "<p class='rz-block'>&lt;script&gt;alert(1)&lt;/script&gt;</p>"
    "<p class='rz-block'>100% &amp; \\TeX</p>"
)

DOC = {
    "name": "Priya Sharma",
    "contact": ["priya@example.com"],
    "sections": [{"heading": "Summary", "kind": "summary", "lead": [{"text": "Backend engineer."}]}],
}


def _post(client, **extra):
    return client.post("/print", json={"html": HTML, "document": DOC, **extra})


def _pdf(body) -> pymupdf.Document:
    return pymupdf.open(stream=base64.b64decode(body["file"]), filetype="pdf")


def test_print_returns_an_a4_pdf(client):
    response = _post(client)
    assert response.status_code == 200
    body = response.json()
    assert body["renderer"] == "chromium"
    assert body["pages"] == 1
    with _pdf(body) as pdf:
        assert abs(pdf[0].rect.width - 595.28) < 1


def test_count_only_returns_pages_without_a_file(client):
    body = _post(client, count_only=True).json()
    assert body["file"] is None
    assert body["pages"] == 1


def test_print_keeps_special_characters_as_text(client):
    with _pdf(_post(client).json()) as pdf:
        text = pdf[0].get_text()
    assert "<script>alert(1)</script>" in text
    assert "100% & \\TeX" in text


def test_blocks_never_split_across_pages(client):
    blocks = "".join(
        "<div class='rz-block'>" + "".join(f"<div>B{n}:{k}</div>" for k in range(5)) + "</div>"
        for n in range(80)
    )
    body = client.post("/print", json={"html": _page(blocks), "document": DOC}).json()
    with _pdf(body) as pdf:
        assert pdf.page_count > 1
        for page in pdf:
            first = page.get_text().strip().splitlines()[0]
            assert re.fullmatch(r"B\d+:0", first), first


def test_rejects_html_over_4mb(client):
    response = client.post("/print", json={"html": "x" * 4_000_001, "document": DOC})
    assert response.status_code == 413
    assert response.json()["detail"] == "html over 4 MB"


def test_print_timeout_raises_and_drops_the_browser(monkeypatch):
    import asyncio

    async def hang(html):
        await asyncio.sleep(5)

    monkeypatch.setattr(printer, "_print", hang)
    with pytest.raises(printer.PrintError):
        asyncio.run(printer.print_html("<p>x</p>", timeout=0.1))
    assert printer._browser is None


def test_print_falls_back_to_drawn_renderer(monkeypatch):
    async def boom(html, timeout=15.0):
        raise printer.PrintError("no chromium")

    monkeypatch.setattr(printer, "print_html", boom)
    with TestClient(main.app) as client:
        body = _post(client).json()
    assert body["renderer"] == "fallback"
    assert body["pages"] >= 1
    with _pdf(body) as pdf:
        assert "Priya Sharma" in pdf[0].get_text()


#: The real print HTML from the web app (`renderResumeHtml`), regenerated by
#: `npm run fixture:print` (scripts/make-print-fixture.ts) whenever RESUME_CSS or ResumePage changes.
REAL_HTML = (Path(__file__).parent / "fixtures" / "resume-print.html").read_text()

#: A4 is 595.28pt wide and the template's margin is 40pt on each side.
LEFT, RIGHT = 40.0, 595.28 - 40.0


def test_real_print_html_sits_inside_the_40pt_margins(chromium):
    """The printed page has the screen's geometry: no default body margin
    shifting the text in, so wraps and page breaks match the preview."""
    import asyncio

    async def print_once():
        # Shut the browser down on the loop that launched it: a browser left
        # bound to a closed loop hangs the next app shutdown.
        try:
            return await printer.print_html(REAL_HTML)
        finally:
            await printer.shutdown()

    data = asyncio.run(print_once())
    with pymupdf.open(stream=data, filetype="pdf") as pdf:
        spans = [
            (span["bbox"], span["text"])
            for block in pdf[0].get_text("dict")["blocks"]
            for line in block.get("lines", [])
            for span in line["spans"]
            if span["text"].strip()
        ]
    left = min(bbox[0] for bbox, _ in spans)
    # The entry dates are right-aligned: they end at the right margin.
    dates = [bbox[2] for bbox, text in spans if "2023" in text or "Present" in text]
    assert abs(left - LEFT) <= 1, left
    assert dates and abs(max(dates) - RIGHT) <= 1, dates


def test_timeout_close_is_bounded_when_the_browser_is_wedged(monkeypatch):
    """A wedged browser can hang close() too; the timeout path must still
    return promptly and drop the browser."""
    import asyncio
    import time

    async def hang(*_args, **_kwargs):
        await asyncio.sleep(60)

    monkeypatch.setattr(printer, "_print", hang)
    monkeypatch.setattr(printer, "_close", hang)
    monkeypatch.setattr(printer, "CLOSE_TIMEOUT", 0.2)
    started = time.monotonic()
    with pytest.raises(printer.PrintError):
        asyncio.run(printer.print_html("<p>x</p>", timeout=0.1))
    assert time.monotonic() - started < 2


def test_chromium_launches_without_dev_shm(monkeypatch):
    """Containers give /dev/shm 64 MB; Chromium must not depend on it."""
    import asyncio

    seen = {}

    class FakeChromium:
        async def launch(self, **kwargs):
            seen.update(kwargs)
            raise RuntimeError("stop here")

    class FakePlaywright:
        chromium = FakeChromium()

        async def stop(self):
            pass

    class Starter:
        async def start(self):
            return FakePlaywright()

    monkeypatch.setattr(printer, "async_playwright", lambda: Starter())
    monkeypatch.setattr(printer, "_browser", None)
    monkeypatch.setattr(printer, "_playwright", None)
    with pytest.raises(RuntimeError):
        asyncio.run(printer._get_browser())
    assert "--disable-dev-shm-usage" in seen.get("args", [])


def test_dockerfile_installs_chromium_where_the_runtime_looks():
    dockerfile = (Path(__file__).parents[1] / "Dockerfile").read_text()
    env = dockerfile.find("PLAYWRIGHT_BROWSERS_PATH=/ms-playwright")
    install = dockerfile.find("playwright install")
    assert 0 <= env < install


def test_fallback_render_and_page_count_run_off_the_event_loop(monkeypatch):
    """The drawn fallback and the pymupdf count are CPU work; on the event
    loop they would stall every other request while they run."""
    offloaded = []
    real = main.run_in_threadpool

    async def spy(func, *args, **kwargs):
        offloaded.append(getattr(func, "__name__", repr(func)))
        return await real(func, *args, **kwargs)

    async def boom(html, timeout=15.0):
        raise printer.PrintError("no chromium")

    monkeypatch.setattr(main, "run_in_threadpool", spy)
    monkeypatch.setattr(printer, "print_html", boom)
    with TestClient(main.app) as client:
        assert _post(client).json()["renderer"] == "fallback"
    assert "render_template" in offloaded
    assert "_page_count" in offloaded
